[package]
name = "pi"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
clearscreen = "4.0.1"
fs_extra = "1.3.0"
inquire = "0.7.5"
regex = "1.11.1"
